apiVersion: networking.k8s.io/v1
kind: Ingress
{{- with .Values.ingress }}
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ default "default" $.Values.deployment.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ $.Release.Name }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ $.Release.Name }}
            port:
              number: 80
{{- end }}