apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-svc
  namespace: {{ default "default" .namespace}}
  labels:
    app: {{ $.Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Release.Name }}
