deployment:
  namespace: example
  replicaCount: 1
  revisionHistory: 2
  containers:
    ports: 80
    image:
      repository: 211104/argo-rollouts
      tag: v0.0.1

service:
  type: ClusterIP
  port: 80